void genInitialize();
void genStartDataSegment();
void genStartTextSegment();
void genFinalize();
void genCalc(ThreeAddr *threeAddrTable, NodeType nType, Symbol *symbolTable);
void genCalcs(ThreeAddr *threeAddrTable, Symbol *symbolTable);
void genExpression(Node *np, Symbol *symbolTable);
void genArrayElOffset(Node *np, ArrayIndex *ip, Symbol *symbolTable);
void genTerminationNodeLoad(Node *np, char *regLabel, Symbol *symbolTable);
void genCondition(Node *np, Symbol *symbolTable, char *label);
void genAssignment(Node *np, Symbol *symbolTable);
void genIfBranch(Node *np, Symbol *symbolTable);
void genForLoop(Node *np, Symbol *symbolTable);
void genWhileLoop(Node *np, Symbol *symbolTable);
