kadai1:
	gcc kadai1.c -o kadai1

kadai2:
	gcc kadai2.c -o kadai2

kadai3:
	gcc kadai3.c -o kadai3

run1:
	./kadai3 | ./kadai1

run2:
	./kadai2 | ./kadai3

clean:
	rm -rf *~ kadai1 kadai2 kadai3 a.out

# End of file (Makefile)
