server:
	gcc -Wall meibo_server.c -o meibo_server
	./meibo_server
	rm -rf *~ meibo_server

client:
	gcc -Wall client.c -o client
	./client
	rm -rf *~ client

clean:
	rm -rf *~ meibo_server client

# End of file (Makefile)
